// Package task defines the core domain entities, value objects, and business rules
// for task management. This package is the innermost layer of Clean Architecture
// and should not depend on any external packages or frameworks.
package task

import (
	"database/sql/driver"
	"encoding/json"
	"time"
)

// Status represents the current lifecycle state of a task.
// It is a type-safe enumeration of valid task statuses.
type Status string

const (
	// StatusNew indicates a newly created task that hasn't been started yet.
	StatusNew Status = "new"
	// StatusInProgress indicates a task that is currently being worked on.
	StatusInProgress Status = "in_progress"
	// StatusDone indicates a completed task.
	StatusDone Status = "done"
)

// RecurrenceType defines the strategy for generating recurring task instances.
// Each type requires specific fields in the RecurrenceRule struct.
type RecurrenceType string

const (
	// RecurrenceDaily generates tasks every N days.
	// Requires RecurrenceRule.Interval to be set.
	RecurrenceDaily RecurrenceType = "daily"

	// RecurrenceMonthly generates tasks on a specific day of each month.
	// Requires RecurrenceRule.DayOfMonth to be set (1-31).
	RecurrenceMonthly RecurrenceType = "monthly"

	// RecurrenceSpecific generates tasks only on explicitly provided dates.
	// Requires RecurrenceRule.Dates to be set with YYYY-MM-DD formatted strings.
	RecurrenceSpecific RecurrenceType = "specific_dates"

	// RecurrenceParity generates tasks on even or odd days of the month.
	// Requires RecurrenceRule.Parity to be set to "even" or "odd".
	RecurrenceParity RecurrenceType = "parity"
)

// RecurrenceRule contains the configuration parameters for recurring task generation.
// It is stored as a JSONB column in PostgreSQL, allowing flexible schema evolution
// without requiring database migrations for new recurrence types.
//
// The fields used depend on the RecurrenceType:
//   - daily: Interval must be set (>0)
//   - monthly: DayOfMonth must be set (1-31)
//   - specific_dates: Dates must be set (non-empty slice of YYYY-MM-DD strings)
//   - parity: Parity must be set ("even" or "odd")
type RecurrenceRule struct {

	// Interval specifies the number of days between task occurrences.
	// Used only with RecurrenceDaily.
	// Example: 1 = every day, 2 = every other day.
	Interval int `json:"interval,omitempty"`

	// DayOfMonth specifies the day of the month (1-31) when the task should occur.
	// Used only with RecurrenceMonthly.
	// For months with fewer days (e.g., February), the task is scheduled on the last day.
	DayOfMonth int `json:"day_of_month,omitempty"`

	// Dates contains a list of specific dates when tasks should be generated.
	// Used only with RecurrenceSpecific.
	// Dates must be formatted as YYYY-MM-DD (e.g., "2026-04-10").
	Dates []string `json:"dates,omitempty"`

	// Parity determines whether tasks are generated on even or odd days.
	// Used only with RecurrenceParity.
	// Valid values: "even", "odd".
	Parity string `json:"parity,omitempty"`
}

// Task is the central domain entity representing a task in the system.
// It supports both regular one-time tasks and recurring task templates.
//
// Regular tasks (IsTemplate = false):
//   - Represent a single unit of work scheduled for a specific date.
//   - May optionally reference a ParentTemplateID if generated from a template.
//
// Template tasks (IsTemplate = true):
//   - Define the rules for generating recurring task instances.
//   - Require RecurrenceType and RecurrenceRule to be set.
//   - Are not displayed in regular task lists.
type Task struct {
	// ID is the unique identifier of the task.
	// It is auto-generated by the database on creation.
	ID int64 `json:"id"`

	// Title is a short, human-readable summary of the task.
	// This field is required.
	Title string `json:"title"`

	// Description provides additional details about the task.
	// May be empty.
	Description string `json:"description"`

	// Status indicates the current lifecycle state of the task.
	// Defaults to StatusNew if not provided.
	Status Status `json:"status"`

	// CreatedAt is the timestamp when the task was created.
	// Set automatically on creation and never updated.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the task was last modified.
	// Updated automatically on every change.
	UpdatedAt time.Time `json:"updated_at"`

	// ScheduledAt is the date and time when the task should be executed.
	// For regular tasks, this represents the planned execution time.
	// For templates, this field is ignored.
	ScheduledAt time.Time

	// RecurrenceType defines the recurrence strategy for template tasks.
	// Must be set when IsTemplate is true.
	// Ignored for regular tasks.
	RecurrenceType RecurrenceType `json:"recurrence_type,omitempty"`

	// RecurrenceRule contains the configuration parameters for recurrence.
	// Must be set when RecurrenceType is specified.
	// The specific fields required depend on the RecurrenceType.
	RecurrenceRule *RecurrenceRule `json:"recurrence_rule,omitempty"`

	// IsTemplate indicates whether this task is a template for recurring tasks.
	// When true, this task defines rules for generating instances.
	// When false, this is a concrete task instance.
	IsTemplate bool `json:"is_template"`

	// ParentTemplateID references the template that generated this task.
	// Nil for manually created tasks and for templates themselves.
	// Used to prevent duplicate generation for the same date.
	ParentTemplateID *int64 `json:"parent_template_id,omitempty"`
}

// Scan implements the sql.Scanner interface for reading JSONB data from PostgreSQL.
// This method is called automatically by the pgx driver when scanning a row
// that contains a JSONB column into a RecurrenceRule struct.
//
// If the database value is NULL, Scan returns nil and leaves the struct unchanged.
func (r *RecurrenceRule) Scan(value interface{}) error {
	if value == nil {
		return nil
	}
	b := value.([]byte)
	return json.Unmarshal(b, r)
}

// Value implements the driver.Valuer interface for writing JSONB data to PostgreSQL.
// This method is called automatically by the pgx driver when inserting or updating
// a RecurrenceRule struct in a JSONB column.
func (r RecurrenceRule) Value() (driver.Value, error) {
	return json.Marshal(r)
}

// Valid checks if the status is one of the defined constants.
// This method ensures type safety when working with external input.
func (s Status) Valid() bool {
	switch s {
	case StatusNew, StatusInProgress, StatusDone:
		return true
	default:
		return false
	}
}
