// Package handlers provides HTTP request/response handling for the Task Service API.
// It contains DTOs (Data Transfer Objects) that define the shape of JSON payloads
// and conversion functions between domain entities and API representations.
package handlers

import (
	"time"

	taskdomain "example.com/taskservice/internal/domain/task"
)

// TaskMutationDTO represents the JSON structure for creating or updating a task.
// It serves as the input contract for POST /api/v1/tasks and PUT /api/v1/tasks/{id}.
//
// Fields with the `omitempty` tag are optional in the JSON payload.
// The API will apply default values or preserve existing values when these fields are omitted.
//
// Important: For update operations (PUT), only the fields explicitly provided
// in the JSON payload will be modified. Omitted fields retain their current values.
type TaskMutationDTO struct {
	// Title is the short summary of the task.
	// Required for both create and update operations.
	Title string `json:"title"`

	// Description provides additional task details.
	// Optional - defaults to empty string if not provided.
	Description string `json:"description"`

	// Status indicates the current lifecycle state of the task.
	// Valid values: "new", "in_progress", "done".
	// Optional for create (defaults to "new"). Required for update.
	Status taskdomain.Status `json:"status"`

	// ScheduledAt is the planned execution date and time in UTC.
	// Format: RFC3339 (e.g., "2026-04-10T09:00:00Z").
	// Optional - if not provided, the task is created without a scheduled date.
	ScheduledAt time.Time `json:"scheduled_at"`

	// RecurrenceType defines the recurrence strategy for template tasks.
	// Required when IsTemplate is true. Ignored for regular tasks.
	// Valid values: "daily", "monthly", "specific_dates", "parity".
	RecurrenceType taskdomain.RecurrenceType `json:"recurrence_type,omitempty"`

	// RecurrenceRule contains the configuration parameters for recurrence.
	// Required when RecurrenceType is set. The specific fields required
	// depend on the chosen RecurrenceType.
	RecurrenceRule *taskdomain.RecurrenceRule `json:"recurrence_rule,omitempty"`

	// IsTemplate indicates whether this task is a recurring template.
	// When true, RecurrenceType and RecurrenceRule must be provided.
	// When false (default), this is a concrete task instance.
	IsTemplate bool `json:"is_template,omitempty"`

	// ParentTemplateID references the template that generated this task.
	// Used internally for generated recurring instances. Should not be set
	// manually by API clients.
	ParentTemplateID *int64 `json:"parent_template_id,omitempty"`
}

// TaskDTO represents the JSON structure for task responses.
// It is the output contract for all task-related endpoints that return task data.
//
// Unlike TaskMutationDTO, this structure includes read-only fields such as
// ID, CreatedAt, and UpdatedAt that are generated by the system.
//
// Fields with zero values are omitted from the JSON response via the `omitempty` tag.
type TaskDTO struct {
	// ID is the unique identifier of the task.
	// Generated by the database on creation.
	ID int64 `json:"id"`

	// Title is the short summary of the task.
	Title string `json:"title"`

	// Description provides additional task details.
	Description string `json:"description"`

	// Status indicates the current lifecycle state of the task.
	Status taskdomain.Status `json:"status"`

	// CreatedAt is the timestamp when the task was created.
	// Set automatically on creation and never updated.
	// Format: RFC3339 in UTC.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the task was last modified.
	// Updated automatically on every change.
	// Format: RFC3339 in UTC.
	UpdatedAt time.Time `json:"updated_at"`

	// ScheduledAt is the planned execution date and time in UTC.
	// Format: RFC3339 (e.g., "2026-04-10T09:00:00Z").
	// Zero value (0001-01-01T00:00:00Z) indicates no scheduled date.
	ScheduledAt time.Time `json:"scheduled_at"`

	// RecurrenceType defines the recurrence strategy for template tasks.
	// Omitted from response when empty.
	RecurrenceType taskdomain.RecurrenceType `json:"recurrence_type,omitempty"`

	// RecurrenceRule contains the configuration parameters for recurrence.
	// Omitted from response when nil.
	RecurrenceRule *taskdomain.RecurrenceRule `json:"recurrence_rule,omitempty"`

	// IsTemplate indicates whether this task is a recurring template.
	// Omitted from response when false (default behavior).
	IsTemplate bool `json:"is_template,omitempty"`

	// ParentTemplateID references the template that generated this task.
	// Omitted from response when nil.
	ParentTemplateID *int64 `json:"parent_template_id,omitempty"`
}

// NewTaskDTO converts a domain Task entity into a TaskDTO for API responses.
// This function acts as an anti-corruption layer between the domain model
// and the API contract, ensuring that internal changes don't leak to clients.
//
// The conversion is straightforward - all fields are copied as-is because
// the domain model and DTO share the same structure by design.
//
// Example usage:
//
//	task := &taskdomain.Task{ID: 1, Title: "Example", ...}
//	dto := NewTaskDTO(task)
//	json.NewEncoder(w).Encode(dto)
func NewTaskDTO(task *taskdomain.Task) TaskDTO {
	return TaskDTO{
		ID:               task.ID,
		Title:            task.Title,
		Description:      task.Description,
		Status:           task.Status,
		CreatedAt:        task.CreatedAt,
		UpdatedAt:        task.UpdatedAt,
		RecurrenceType:   task.RecurrenceType,
		RecurrenceRule:   task.RecurrenceRule,
		IsTemplate:       task.IsTemplate,
		ParentTemplateID: task.ParentTemplateID,
		ScheduledAt:      task.ScheduledAt,
	}
}
